### ISSUE TITLE
cmd-id doesn't seem to work yet in advancedb

### ISSUE THREAD

**Issue by ghost** [natmeox/hlm-suite#3]
Thank you for the two pull requests you did, to help make cmd-id available. :D
The one thing that errors now, when testing in advancedb, is:
Error in line 39: Unrecognized word rtn-dohelp.
That's odd though since rtn-dohelp is defined in lib-bits and I had it registered right. |3  Or I hope I did.  As mentioned before, I'm somewhat novice to wizstuff.
When I get rid of rtn-dohelp in cmd-id though, the id command compiles and works!! :D  It's colorful~
(note, if testing in advancedb yourself, you'll need to give One a MUCKER bit and register the included but unregistered lib-case yourself, and also give it an M3)

It's possible I just didn't figure out how to get it registered right, even though I just pasted it in as-is, including with its own set and register commands.

**Comment by ghost** [comment]
Alternatively when testing, you can delete the $include $lib/case line when testing on fb7 since all those are now included in fb7 itself now.  @wyld-sw told me of that just now.

**Comment by natmeox** [comment]
Hi, @nyanster! I was able to reproduce this issue in a new advancedb. It looked like I had omitted the `$pubdef` declarations from the `lib-bits.muf`, such that those words weren't immediately callable by calling libraries.

Does the lib/bits from #4 seem to work for you?

**Comment by ghost** [comment]
Thanks :D
